### ISSUE TITLE
Не появились оценки за некоторые тренировки

### ISSUE THREAD

**Issue by Plyushchenko** [OSLL/web_speech_trainer#145]
605b497bb37490f1550634d7 | woghan | Nikita Vaganov | Wed, 24 Mar 2021 14:15:23 GMT | ...
605b5658b37490f1550634fd | woghan | Nikita Vaganov | Wed, 24 Mar 2021 15:10:16 GMT | ...
605b566cb37490f15506350d | woghan | Nikita Vaganov | Wed, 24 Mar 2021 15:10:36 GMT | ...
605b5ca4b37490f155063521 | ant.filatov | Антон Филатов | Wed, 24 Mar 2021 15:37:08 GMT |  ...

**Comment by Plyushchenko** [comment]
+ docker logs wstdeploy_audio_processor_1
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/app/audio_processor.py", line 32, in <module>
    audio_processor.run()
  File "/app/app/audio_processor.py", line 19, in run
    recognized_audio = self.audio_recognizer.recognize(presentation_record_file)
  File "/app/app/audio_recognizer.py", line 47, in recognize
    temp_wav_file = utils.convert_from_mp3_to_wav(audio)
  File "/app/app/utils.py", line 20, in convert_from_mp3_to_wav
    sound = AudioSegment.from_mp3(audio) \
  File "/usr/local/lib/python3.6/dist-packages/pydub/audio_segment.py", line 796, in from_mp3
    return cls.from_file(file, 'mp3', parameters=parameters)
  File "/usr/local/lib/python3.6/dist-packages/pydub/audio_segment.py", line 775, in from_file
    p.returncode, p_err.decode(errors='ignore') ))
pydub.exceptions.CouldntDecodeError: Decoding failed. ffmpeg returned error code: 1

Output from ffmpeg/avlib:

ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100
[cache @ 0x562b7d08f380] Inner protocol failed to seekback end : -38
    Last message repeated 1 times
[mp3 @ 0x562b7d08e940] decoding for stream 0 failed
[cache @ 0x562b7d08f380] Inner protocol failed to seekback end : -38
    Last message repeated 1 times
[mp3 @ 0x562b7d08e940] Could not find codec parameters for stream 0 (Audio: mp3, 0 channels, s16p): unspecified frame size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mp3, from 'cache:pipe:0':
  Duration: N/A, start: 0.000000, bitrate: N/A
    Stream #0:0: Audio: mp3, 0 channels, s16p
Stream mapping:
  Stream #0:0 -> #0:0 (mp3 (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Error while decoding stream #0:0: Invalid data found when processing input
Finishing stream 0:0 without any data written to it.
[abuffer @ 0x562b7d09eee0] Value inf for parameter 'time_base' out of range [0 - 2.14748e+09]
    Last message repeated 3 times
[abuffer @ 0x562b7d09eee0] Error setting option time_base to value 1/0.
[graph_0_in_0_0 @ 0x562b7d09ede0] Error applying options to the filter.
Error configuring filter graph
[cache @ 0x562b7d08f380] Statistics, cache hits:32783 cache misses:32
Conversion failed!

/usr/local/lib/python3.6/dist-packages/librosa/core/spectrum.py:224: UserWarning: n_fft=2048 is too small for input signal of length=512
  n_fft, y.shape[-1]
/usr/local/lib/python3.6/dist-packages/librosa/core/spectrum.py:224: UserWarning: n_fft=2048 is too small for input signal of length=0
  n_fft, y.shape[-1]
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/app/audio_processor.py", line 32, in <module>
    audio_processor.run()
  File "/app/app/audio_processor.py", line 19, in run
    recognized_audio = self.audio_recognizer.recognize(presentation_record_file)
  File "/app/app/audio_recognizer.py", line 48, in recognize
    Denoiser.process_wav_to_wav(temp_wav_file, temp_wav_file, noise_length=3)
  File "/app/playground/noise_reduction/denoiser.py", line 76, in process_wav_to_wav
    denoised_audio = cls.process_seg_to_seg(audio, noise_length)
  File "/app/playground/noise_reduction/denoiser.py", line 57, in process_seg_to_seg
    frame_rate=rate
  File "/app/playground/noise_reduction/denoiser.py", line 27, in reduce_by_first_n_seconds
    reduced = cls.reduce_by_example(data, noise, frame_rate)
  File "/app/playground/noise_reduction/denoiser.py", line 18, in reduce_by_example
    noise_clip=noise_np
  File "/usr/local/lib/python3.6/dist-packages/noisereduce/noisereduce.py", line 275, in reduce_noise
    use_tensorflow=use_tensorflow,
  File "/usr/local/lib/python3.6/dist-packages/noisereduce/noisereduce.py", line 15, in _stft
    y=y, n_fft=n_fft, hop_length=hop_length, win_length=win_length, center=True
  File "/usr/local/lib/python3.6/dist-packages/librosa/core/spectrum.py", line 228, in stft
    y = np.pad(y, int(n_fft // 2), mode=pad_mode)
  File "<__array_function__ internals>", line 6, in pad
  File "/usr/local/lib/python3.6/dist-packages/numpy/lib/arraypad.py", line 819, in pad
    "'constant' or 'empty'".format(axis)
ValueError: can't extend empty axis 0 using modes other than 'constant' or 'empty'
+ docker logs wstdeploy_recognized_presentation_processor_1
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/app/recognized_presentation_processor.py", line 36, in <module>
    recognized_presentation_processor.run()
  File "/app/app/recognized_presentation_processor.py", line 23, in run
    presentation = Presentation(recognized_presentation, slide_switch_timestamps)
  File "/app/app/presentation.py", line 12, in __init__
    self.slides = self.split_into_slides(recognized_presentation, slide_switch_timestamps)
  File "/app/app/presentation.py", line 25, in split_into_slides
    'end_timestamp': slide_switch_timestamps[i + 1],
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/app/recognized_presentation_processor.py", line 36, in <module>
    recognized_presentation_processor.run()
  File "/app/app/recognized_presentation_processor.py", line 23, in run
    presentation = Presentation(recognized_presentation, slide_switch_timestamps)
  File "/app/app/presentation.py", line 12, in __init__
    self.slides = self.split_into_slides(recognized_presentation, slide_switch_timestamps)
  File "/app/app/presentation.py", line 25, in split_into_slides
    'end_timestamp': slide_switch_timestamps[i + 1],
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/app/recognized_presentation_processor.py", line 36, in <module>
    recognized_presentation_processor.run()
  File "/app/app/recognized_presentation_processor.py", line 23, in run
    presentation = Presentation(recognized_presentation, slide_switch_timestamps)
  File "/app/app/presentation.py", line 12, in __init__
    self.slides = self.split_into_slides(recognized_presentation, slide_switch_timestamps)
  File "/app/app/presentation.py", line 25, in split_into_slides
    'end_timestamp': slide_switch_timestamps[i + 1],
IndexError: list index out of range
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/app/recognized_presentation_processor.py", line 36, in <module>
    recognized_presentation_processor.run()
  File "/app/app/recognized_presentation_processor.py", line 23, in run
    presentation = Presentation(recognized_presentation, slide_switch_timestamps)
  File "/app/app/presentation.py", line 12, in __init__
    self.slides = self.split_into_slides(recognized_presentation, slide_switch_timestamps)
  File "/app/app/presentation.py", line 25, in split_into_slides
    'end_timestamp': slide_switch_timestamps[i + 1],
IndexError: list index out of range
